package ir.startup.zabanbaz.composeapp.theme

import androidx.compose.ui.graphics.Color

/** Brand and neutral tokens — aligned with live_app system design. */
object AppColors {
    val BrandPrimary = Color(0xFF2563EB)
    val BrandSecondary = Color(0xFF6D28D9)
    val BrandTertiary = Color(0xFF0EA5E9)

    val Neutral0 = Color(0xFFFFFFFF)
    val Neutral10 = Color(0xFFFAFAFA)
    val Neutral50 = Color(0xFFF6F7F9)
    val Neutral900 = Color(0xFF111827)
    val Neutral1000 = Color(0xFF0B1020)
    val AppDarkBackground = Color(0xFF0C0C0C)

    val Success = Color(0xFF0F9D58)
    val Warning = Color(0xFFEAA221)
    val Error = Color(0xFFBA1A1A)
    val Info = Color(0xFF0284C7)
}

/** Material 3 scheme literals — mirrors live_app [AppSchemeColors]. */
internal object AppSchemeColors {
    val Black = Color(0xFF000000)

    val LightPrimary = Color(0xFF1F5BD8)
    val LightPrimaryContainer = Color(0xFFDCE6FF)
    val LightOnPrimaryContainer = Color(0xFF001A4E)
    val LightSecondary = Color(0xFF5E4AA3)
    val LightSecondaryContainer = Color(0xFFE9DDFF)
    val LightOnSecondaryContainer = Color(0xFF1D1144)
    val LightTertiary = Color(0xFF006B91)
    val LightTertiaryContainer = Color(0xFFC7E8FF)
    val LightOnTertiaryContainer = Color(0xFF001E2E)
    val LightError = Color(0xFFBA1A1A)
    val LightErrorContainer = Color(0xFFFFDAD6)
    val LightOnErrorContainer = Color(0xFF410002)
    val LightOnSurface = Color(0xFF171B23)
    val LightSurfaceDim = Color(0xFFD9DCE2)
    val LightSurfaceContainerLow = Color(0xFFF2F4F8)
    val LightSurfaceContainer = Color(0xFFEDEFF4)
    val LightSurfaceContainerHigh = Color(0xFFE7EAF0)
    val LightSurfaceContainerHighest = Color(0xFFE1E4EB)
    val LightOnSurfaceVariant = Color(0xFF434A57)
    val LightOutline = Color(0xFF737B88)
    val LightOutlineVariant = Color(0xFFC3CAD8)
    val LightInverseSurface = Color(0xFF2D3139)
    val LightOnInverseSurface = Color(0xFFEEF1F7)
    val LightInversePrimary = Color(0xFFB6CCFF)
    val LightSurfaceTint = Color(0xFF1F5BD8)

    val DarkPrimary = Color(0xFFB6CCFF)
    val DarkOnPrimary = Color(0xFF002C75)
    val DarkPrimaryContainer = Color(0xFF003E9F)
    val DarkOnPrimaryContainer = Color(0xFFDCE6FF)
    val DarkSecondary = Color(0xFF608DEF)
    val DarkOnSecondary = Color(0xFF111111)
    val DarkSecondaryContainer = Color(0xFF49388A)
    val DarkOnSecondaryContainer = Color(0xFFE9DDFF)
    val DarkTertiary = Color(0xFF89D0FF)
    val DarkOnTertiary = Color(0xFF00344A)
    val DarkTertiaryContainer = Color(0xFF005A7A)
    val DarkOnTertiaryContainer = Color(0xFFC7E8FF)
    val DarkError = Color(0xFFFFB4AB)
    val DarkOnError = Color(0xFF690005)
    val DarkErrorContainer = Color(0xFF93000A)
    val DarkOnErrorContainer = Color(0xFFFFDAD6)
    val DarkOnSurface = Color(0xFFE3E8F0)
    val DarkSurfaceBright = Color(0xFF313843)
    val DarkSurfaceContainerLowest = Color(0xFF06090F)
    val DarkSurfaceContainerLow = Color(0xFF111111)
    val DarkSurfaceContainer = Color(0xFF121212)
    val DarkSurfaceContainerHigh = Color(0xFF171717)
    val DarkSurfaceContainerHighest = Color(0xFF191919)
    val DarkOnSurfaceVariant = Color(0xFFAFAFAF)
    val DarkOutline = Color(0xFF999899)
    val DarkOutlineVariant = Color(0xFF1E1E1E)
    val DarkInverseSurface = Color(0xFFE3E8F0)
    val DarkOnInverseSurface = Color(0xFF2D3139)
    val DarkInversePrimary = Color(0xFF1F5BD8)
    val DarkSurfaceTint = Color(0xFFB6CCFF)
}
